### ISSUE TITLE
include statements

### ISSUE THREAD

**Issue by backfromhiatus** [abhaynayar/nand2tetris#2]
can you add support for #include "filepath" statements in the compiler? My brain is too tiny to do something like that :)

**Comment by abhaynayar** [comment]
That's actually a very interesting idea.

Honestly, even I won't be able to do it without a lot of effort. I feel that the current method of compiling related files in one directory works well, and having an "include" functionality, while useful, will have low reward/effort.

In any case, I am not contributing here anymore, so feel free to take this ahead in your own fork. Best of luck!
